baseurl = "https://mithun.tech"
title = "Mithun K"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Mithun K"
    description = "Personal website of Mithun K"
    keywords = "coding, personal"
    info = "CS Student · Pythonist"
    avatarurl = "img/Mithun.jpeg"
    #gravatar = "john.doe@example.com"
    footercontent = "Pollution is so low that I can see data stored in the cloud."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"
    
# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/k-mithun/"
[[params.social]]
    name = "Xing"
    icon = "fab fa-xing"
    weight = 2
    url = "https://www.xing.com/profile/Mithun_K/cv"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/Mithun-windows-linux"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 4
    url = "https://medium.com/@k.mithun"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "whoami"
            weight = 1
            url = "whoami/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "blogs/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 5
            url = "contact/"


    [languages.de]
        languagename = "Deutsch"
        title = "Mithun"

        [languages.de.params]
            author = "Mithun K"
            info = "CS Student · Pythonist"
            description = "Persönliche Webseite"
            keywords = "coding, personal"
            footercontent = "Die Verschmutzung ist sehr niedrig, dass ich in der Cloud gespeicherte Daten sehen kann."

        [languages.de.menu]

            [[languages.de.menu.main]]
            name = "Wer bin ich?"
            weight = 1
            url = "whoami/"

            [[languages.de.menu.main]]
            name = "Blog"
            weight = 2
            url = "blogs/"

            [[languages.de.menu.main]]
            name = "Projekte"
            weight = 3
            url = "projects/"

            [[languages.de.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "contact/"
